### ISSUE TITLE
Different results from src and src_cvpr????

### ISSUE THREAD

**Issue by hwy1992129** [Juyong/Fast_RNRR#12]
Thanks for sharing the codes. @Juyong @yaoyx689 
I want to register the head of SMPL human model into my 3d scan data for hole filling. The back of a head is hard to scan, and my model has a big hole there. I think non-rigid registration could help. (Do you have any suggestions for it?)

Currently, I am making some tests on synthetic data using Fast_RNRR and NonRigidreg with different methods.
With the same set of source and target data, Fast_RNRR and NonRigidreg with method 3 don't give the same result. Is it caused by a mistake in building or parameters in the scripts????
Fast_RNRR gives a very long straight line. What is this issue?

**Comment by yaoyx689** [comment]
Hi, if the quality of the source mesh is poor (for example, there are many holes), because there may be isolated nodes in the node graph, we did not process it.

In principle, this code can handle partial-to-partial non-rigid registration problem, but it need to adjust the parameters $\nu_a$ and $\nu_r$ to suit for the specific models.  You can add ``paras.Data_initk = *;'' in src/main.cpp to test, and it is related to the overlap rate. Generally it's set between 0.5~3.

There are some differences between Fast_RNRR and NonRigidreg on some parameter settings and details. Their results may be different.

If the source mesh has  a good quality, you can try to modify the parameter settings first to see if it can obtain good results.
