### ISSUE TITLE
The format of point cloud to input

### ISSUE THREAD

**Issue by Tyg23** [Juyong/Fast_RNRR#15]
It says the code supports non-rigid registration from a triangle mesh to a mesh or a point cloud. Then if I want to input a point cloud, what format is supported in this code? And is there any part of the code has to be modified please? Thank you so much

**Comment by yaoyx689** [comment]
Do you mean that the source model (deformed model) is a point cloud?  

If so, you should change the part of building the deformation graph, because we need to compute the geodesic distance in this process, and we use the method which is just suitable for the mesh.

If not, for the target model (fixed model), you can input a point cloud in any form that can be read by OpenMesh(https://www.graphics.rwth-aachen.de/software/openmesh/), such as 
'.ply', '.obj', '.off'.

**Comment by Tyg23** [comment]
Brilliant work, I got it. Thank you so much!

**Comment by sun421-cloud** [comment]
> Brilliant work, I got it. Thank you so much!

Hi, did you change the input  from mesh to point cloud?
