### ISSUE TITLE
Error: Some points cannot be covered under the specified radius, please increase the radius

### ISSUE THREAD

**Issue by chenxhhh** [Juyong/Fast_RNRR#7]
I use this code for face rigistration. when I ran this code, the error occured.
this is the source img
<img width="333" alt="image" src="https://user-images.githubusercontent.com/30165143/113711841-01caa880-9718-11eb-9e2b-618436677698.png">
this is the target img
<img width="312" alt="image" src="https://user-images.githubusercontent.com/30165143/113711967-26268500-9718-11eb-8b69-01e9a7434aa2.png">
I would be appreciate it if you can tell me how to fix this error.

**Comment by yaoyx689** [comment]
Thank you for your feedback. This is because the node sampling method is uniform. When the model points are not very uniform and the sampling radius is small, some sampling points are not covered by any mesh vertices, and this error will be caused. 
So 
1) Make sure that there are no isolated vertices in the input source model.
2) Increase node sampling radius of deformation graph by setting "paras.uni_sample_radio" with a bigger value in "main.cpp".  This operation will work.

**Comment by chenxhhh** [comment]
Thank you for your reply. It works now.

**Comment by xiecookie** [comment]
hello, could I ask how you solved this question?by changing the "uni_sample_radio" parameter？

**Comment by sun421-cloud** [comment]
> Thank you for your reply. It works now.

hello, I change the parameter called "uni_sample_radio", but the error "Some points cannot be covered under the specified radius, please increase the radius" is still exist. Have you ever come across this problem?

**Comment by seunguk-do** [comment]
hello, I have same problem too. I have tried to apply this code to the meshes attached below. I've tried several values of "uni_sample_radio", but they all failed. Can you give me any advice
?
<img width="131" alt="Screen Shot 2022-01-25 at 3 53 41 PM" src="https://user-images.githubusercontent.com/49643376/150926302-9717ab5c-074e-411f-9650-88d0c8f5bc37.png">
<img width="112" alt="Screen Shot 2022-01-25 at 3 53 49 PM" src="https://user-images.githubusercontent.com/49643376/150926316-7225930e-d52f-4770-9f53-f2f61c0e0546.png">
